name: simple
description: "A calculator with basic math functions, currently being used for Google Playstore publishing experience."

publish_to: 'none'

version: 0.0.2+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable:
  flutter_bloc:
  google_fonts:
  in_app_update: 4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true